# SPDX-FileCopyrightText: © 2025 Stefan Siegel <ssiegel@sdas.net>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    "docs/**",
    "example/**",
    "README.md"
]
SPDX-FileCopyrightText = "© 2025 Stefan Siegel <ssiegel@sdas.net>"
SPDX-License-Identifier = "CC-BY-SA-4.0 OR GPL-3.0-or-later"
